"""users: add admin and superuser

Revision ID: e6bcc69e1e75
Revises: 925296cc97eb
Create Date: 2023-07-16 11:42:10.953213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e6bcc69e1e75"
down_revision = "925296cc97eb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_admin", sa.Boolean(), server_default="false", nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "is_superuser", sa.Boolean(), server_default="false", nullable=False
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("is_superuser")
        batch_op.drop_column("is_admin")

    # ### end Alembic commands ###
