"""add hashed password to users

Revision ID: 925296cc97eb
Revises: d1589b79ae5c
Create Date: 2023-07-11 16:38:48.576627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "925296cc97eb"
down_revision = "d1589b79ae5c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("hashed_password", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###
